### ISSUE TITLE
D feladatai

### ISSUE THREAD

**Issue by gedand** [gedand/452c8c82-Virucid#2]
- [x]  DB táblák átírása Követelmények doksi szerint
- [x]  try-catchek használata, hogy ne igazán szállhasson el a program
- [x]  HTTP kódok használata válaszoknál (200 OK, 401 Wrong username or password, 403 Forbidden, stb.)
- [x] Írj egy requirements.txt fájlt, amiben enterrel elválasztva leírod, hogy milyen package-eket kell feltelepíteni ahhoz, hogy működjön az app (pl. Flask-SQLAlchemy)
- [x] Külön fájlokban lehetnének a különböző endpointokat megvalósító részek, hogy átláthatóbb legyen a kód
- [x]  POST kéréseknél Bodyban legyenek a paraméterek, semmiképp nem URL-ben

**Comment by mucsacso03** [comment]
Done

**Comment by gedand** [comment]
A HTTP kódok miatt reopenelem, de lehet azt én megcsinálom
